language: php
php:
- 7.1
before_script:
- composer self-update
- composer install
- chmod -R 777 storage
script:
- mv .env.example .env
- php artisan key:generate
# Run PHPUnit and get coverage
- mkdir -p build/logs
- chmod -R 777 build/logs
- vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
# Let coveralls reflect coverage
- travis_retry php vendor/bin/coveralls -v
notifications:
  slack:
    secure: tkF3LI7BbnSrdvY42LF21ZV11XHWsX2ABhnVa7Gir+1cGKEUjoiABdHUsJlzl62Fh4KnrpUlYr6BOMF7qoLQ0PD+ik7dM0A76I2tIyuXAlgEPvxJviDwnGD5nQd5FHk9L3m/MvZ37rtj/r6ImAXyZvAbfwIkkODTpkd1/pl437VRTWEkX8tgB3nQ1H8PxdifvkYQpFzQioeVqEZ0+DB4mLMgHlv68YbKptBpZ8bB5aaNd6VU9DAsRh5moP1UVN4VqrSSPfvEts5i3NoRMdjBKat7w1mfVCA7FeBD71Y4c5AoWXAeRTqWmBRyxFzX5fg/LQKSV1ZE4skPOugkObRm57+YFWQ9NcEJcqN0ejbIXlBwLcRa9l26ge1VkR0P0qNdMNbDLsJHSOX8d1EgD4pxbqfOhONQjx3YbK0/mbF0qO1pz6taBVJfsEI9ZU+OI1/90/WxUsOtTPbcM4THn/Y/OsWJ8V0R6k6GCU6pPATiPPrb5b7azfYTCsvfQyBv8+yz0PZ6D8VtZ2xpR5bpH0SxSMycrLbNtQE2ujYb2BKlO3PgiCOSTSrlVGHx4kh9JEFY/r8ZYzze6GSY9jqhRHZvMxybMPC7Ju6ymXyqmaN1xNZz9LTfem8f3JlTt9U4V3atMQnXnd0QGtO1ur5aAjN5XZPLotlNfJC8gaQdD68XW+Q=
env:
  global:
    secure: TrDU8WIhCSH6ypEgACISGBa8mbPh3XfPnPzMgrWo8i4c/lcj7HK3VE7qp4PsuwRwLsghhk8uplpVOfHdyAvj38yJEYkXia/+zYT43Hw5Ve6JTWqhjZmaWXGf6hzsaCqZQW2MaM7M4OQFyCDLlO2/HQ8yYKeM0lkQZqcLwbVZLUOrJ42Bhjf62bGrxfy7T5MR0wTO9QFc0Hq3Uo9hnDTxBxPoyejJcqYtgJZecimfGwWWncAGSZdzyD2nduzCHeNrwPWH/f+YNRh5kRAJajS0/l3pd6fcf4d0acbvWR5REnizJTpqhxqToT8YTstGK0FZzuYOmSmSTMcnoAMvfRhX80nUkznrIQ2ge3c8nJx78V7CJJ2+HoKX71BYUTxtn5dBuxK7pnT0f161AFMKE/1b65Telc8RIOm1yQ8og9jKNWv5dsfz0RbGBdYPNh/HK6IElGwfSmw3GydKuHYMsjyIB9YYsV+GVa3Sow+0k+GCT6PIok2xXmUnQIVuVkt5UIkIotiyUEWd0r3apR+ZRNY0u/hmKwZfwGuPIAVKH1v0S3ixCX7NxTxy6H1kXJzT85CTd5QYv8TevAGOZ9FnYtskdXFovIbKdVmgh0ZL0cGVFNh0kUQ0V7j0oasvZk+3ZUTDkon9UY9KhnKR3MdL/psZ8snI0nVvtaT04cUM3TrT9KE=
